### ISSUE TITLE
Suggestions on future versions of dynamac

### ISSUE THREAD

**Issue by andyphilips** [andyphilips/dynamac#2]
Suggestions for future issues of dynamac:
-for plots using the "mean" option (or just the mean value in general), add option for horizontal line showing this (suggested by Philipp Lutscher)
-for plots, add small marker to denote when shock is actually taking place (suggested by Philipp Lutscher)

**Comment by hlra** [comment]
Thanks for this great package! Another simple suggestion for future versions could be the possibility to adjust plots labels. This would ideally include the text of the labels as well as text size. When exporting plots, for example with high resolution for publication, this would help a lot.

Cheers,
Lukas

**Comment by andyphilips** [comment]
Thanks Lukas! That's a good idea. Overall, it would be nice to add the ability to send any option that you might use in 'plot' to pass through the function; I'll let you know when we add this capability

**Comment by sorenjordan** [comment]
Lukas, Thanks for the suggestion! We replaced the plotting functions with new ones, and in the next planned release (0.1.9), dynardl.simulation.plot() will accept user-defined labels and other plotting arguments in the standard three-dot way.

**Comment by hlra** [comment]
Great! Looking forward to that and it comes at the right time.
