### ISSUE TITLE
minor bug in console output of dynardl.auto.correlated()

### ISSUE THREAD

**Issue by ugobob99** [andyphilips/dynamac#4]
In function dynardl.auto.correlated(), the code assumes that the 'parameter' output of bgtest() is a single number equal to the maximal order of serial correlation tested, but this is true only for type Chisq. For type F a vector of length 2 with the numbers of degrees of freedom for F is returned (the first one of which is the maximal order) so the current code prints a double output for H0 (only the first is correct).

**Comment by sorenjordan** [comment]
Thank you! The next release will appropriately call to $parameter[1].

**Comment by andyphilips** [comment]
This has been fixed..Thanks!
