### ISSUE TITLE
Error message when trying to Implement Dynamic Simulations of ARDL Models(Page,917)

### ISSUE THREAD

**Issue by Dumkof** [andyphilips/dynamac#9]
dynardl ln_inv ln_inc ln_consump, ///
lags(1, 1, 1) diffs(., 1, 1) ///
shockvar(ln_inc) shockval(-1) ///
time(10) range(30) graph ec

Stata has given Error message.......
. dynardl ln_inv ln_inc ln_consump,lags(1, 1, 1) diffs(., 1, 1) shockvar(ln_inc) shockval(-1) time(10) range(30) graph ec
-----------------------------------------------
Option ec specified, dependent variable to be run in differences
invalid 'parse' 
r(198);

**Comment by andyphilips** [comment]
@Dumkof I'm not getting this error:

clear
cap ado uninstall dynamac
cap ado uninstall dynardl
cap ado uninstall pssbounds
net install dynamac, from(https://github.com/andyphilips/dynamac/raw/gh-pages/Stata/src/) replace

webuse lutkepohl2

dynardl ln_inv ln_inc ln_consump, ///
lags(1, 1, 1) diffs(., 1, 1) ///
shockvar(ln_inc) shockval(-1) ///
time(10) range(30) graph ec

Runs without error. If you run the above and you're still getting an error, could you send me a log file? Also, what's your Stata version?

**Comment by Dumkof** [comment]
Dear Professor,

I received your reply with Thanks. I really appreciate your time.Thanks so much, Professor.

Best regards,

Koffi Dumor

 


    Le dimanche 28 février 2021, 23:25:58 UTC+8, Andrew Q. Philips <notifications@github.com> a écrit :  
 
 


@Dumkof I'm not getting this error:

clear
cap ado uninstall dynamac
cap ado uninstall dynardl
cap ado uninstall pssbounds
net install dynamac, from(https://github.com/andyphilips/dynamac/raw/gh-pages/Stata/src/) replace

webuse lutkepohl2

dynardl ln_inv ln_inc ln_consump, ///
lags(1, 1, 1) diffs(., 1, 1) ///
shockvar(ln_inc) shockval(-1) ///
time(10) range(30) graph ec

Runs without error. If you run the above and you're still getting an error, could you send me a log file? Also, what's your Stata version?

**Comment by Dumkof** [comment]
Dear Professor,
I'm still getting an error message. I do attach my log file. I used Stata 15.1.Thanks, Prof.
    Le mardi 2 mars 2021, 20:11:36 UTC+8, dumor koffi <dumor3000@yahoo.fr> a écrit :  
 
  
Dear Professor,

I received your reply with Thanks. I really appreciate your time.Thanks so much, Professor.

Best regards,

Koffi Dumor

 


    Le dimanche 28 février 2021, 23:25:58 UTC+8, Andrew Q. Philips <notifications@github.com> a écrit :  
 
 


@Dumkof I'm not getting this error:

clear
cap ado uninstall dynamac
cap ado uninstall dynardl
cap ado uninstall pssbounds
net install dynamac, from(https://github.com/andyphilips/dynamac/raw/gh-pages/Stata/src/) replace

webuse lutkepohl2

dynardl ln_inv ln_inc ln_consump, ///
lags(1, 1, 1) diffs(., 1, 1) ///
shockvar(ln_inc) shockval(-1) ///
time(10) range(30) graph ec

Runs without error. If you run the above and you're still getting an error, could you send me a log file? Also, what's your Stata version?

**Comment by Dumkof** [comment]
Dear Professor,
Sorry for my mistakes, it's Ok now. Thanks so much, Professor
    Le mardi 2 mars 2021, 20:48:26 UTC+8, dumor koffi <dumor3000@yahoo.fr> a écrit :  
 
  Dear Professor,
I'm still getting an error message. I do attach my log file. I used Stata 15.1.Thanks, Prof.
    Le mardi 2 mars 2021, 20:11:36 UTC+8, dumor koffi <dumor3000@yahoo.fr> a écrit :  
 
  
Dear Professor,

I received your reply with Thanks. I really appreciate your time.Thanks so much, Professor.

Best regards,

Koffi Dumor

 


    Le dimanche 28 février 2021, 23:25:58 UTC+8, Andrew Q. Philips <notifications@github.com> a écrit :  
 
 


@Dumkof I'm not getting this error:

clear
cap ado uninstall dynamac
cap ado uninstall dynardl
cap ado uninstall pssbounds
net install dynamac, from(https://github.com/andyphilips/dynamac/raw/gh-pages/Stata/src/) replace

webuse lutkepohl2

dynardl ln_inv ln_inc ln_consump, ///
lags(1, 1, 1) diffs(., 1, 1) ///
shockvar(ln_inc) shockval(-1) ///
time(10) range(30) graph ec

Runs without error. If you run the above and you're still getting an error, could you send me a log file? Also, what's your Stata version?
